
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Tue Feb 06 13:54:06 CET 2018
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CHAR_CONST = 43;
  public static final int LPARENT = 2;
  public static final int RPARENT = 3;
  public static final int INCREMENT = 14;
  public static final int CONST = 9;
  public static final int LOWER = 29;
  public static final int CONTINUE = 40;
  public static final int GREATER = 32;
  public static final int NUM_CONST = 41;
  public static final int NOT_BIN_EQUAL = 34;
  public static final int SEMI_COMMA = 36;
  public static final int MINUS = 20;
  public static final int DECREMENT = 15;
  public static final int R_SQUARE_PARENT = 11;
  public static final int COMMA = 5;
  public static final int CLASS = 44;
  public static final int DIV = 22;
  public static final int PLUS = 19;
  public static final int IF = 27;
  public static final int DOT = 28;
  public static final int EOF = 0;
  public static final int RETURN = 39;
  public static final int EQUAL = 17;
  public static final int GREATER_EQUAL = 35;
  public static final int LOGICAL_OR = 25;
  public static final int NEW = 16;
  public static final int error = 1;
  public static final int MUL = 21;
  public static final int BIN_EQUAL = 38;
  public static final int MOD = 23;
  public static final int IDENT = 42;
  public static final int L_SQUARE_PARENT = 10;
  public static final int BREAK = 31;
  public static final int VOID = 13;
  public static final int L_BRACE = 7;
  public static final int ELSE = 26;
  public static final int R_BRACE = 8;
  public static final int READ = 4;
  public static final int WHILE = 33;
  public static final int LOGICAL_AND = 24;
  public static final int LOWER_EQUAL = 30;
  public static final int EXTENDS = 12;
  public static final int PROG = 6;
  public static final int BOOL_CONST = 45;
  public static final int DO = 37;
  public static final int PRINT = 18;
}

